### ISSUE TITLE
Package version 3.0.2

### ISSUE THREAD

**Issue by emisand** [mrahhal/MR.AspNet.Identity.EntityFramework6#14]
Hello @mrahhal,
Can you please publish the nuget package for version 3.0.2.
Version 3.0.1 is not working with the latest version of Identity 3 due to the missing UserTokens store.
I got this to work by downloading the source code and importing the project into my solution, but it is a dirty workaround.

Thank you!

**Comment by mrahhal** [comment]
Hello,

Sorry this took too long. I was planning on solving the 2FA issue before releasing 3.0.2 but things got busy and I completely forgot.

I still have no update on the 2FA issue, so I'll be releasing 3.0.2 with the current fixes.

**Comment by mrahhal** [comment]
(Will close when I release 3.0.2)

**Comment by mrahhal** [comment]
Well that was fast. Please use `3.0.2` and let me know if you face issues.

**Comment by emisand** [comment]
@mrahhal Installed and working, thank you!
