### ISSUE TITLE
ASP.NET RTM Compatibility

### ISSUE THREAD

**Issue by philbern** [mrahhal/MR.AspNet.Identity.EntityFramework6#2]
The latest version doesn't work with the new RTM release of ASP.NET. Getting this error when calling `services.AddIdentity`:

```
Additional information: Could not load type 'Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionExtensions' from assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

Seems like its linked to this change https://github.com/aspnet/DependencyInjection/issues/412

**Comment by NickolasAcosta** [comment]
I am also experiencing this whenever i try to do dotnet ef migrations add or dotnet ef database update

**Comment by mrahhal** [comment]
Yes sorry about that. I still haven't upgraded this to `1.0.0`. I planned to do it on the same day of the release but I was having unexpected issues with VS update 3. I'll release a new version as soon as possible.

**Comment by mrahhal** [comment]
@philbern try updating to `2.0.0`.

**Comment by philbern** [comment]
It's working!

Thanks
