### ISSUE TITLE
Production Use

### ISSUE THREAD

**Issue by mafshin** [mrahhal/MR.AspNet.Identity.EntityFramework6#4]
Hi @mrahhal 

Thanks for the EF6 provider.

What is the status of the project, can we use it in the production code?

**Comment by mrahhal** [comment]
Hi,

I'm using it in several projects running in production.

Granted, I didn't test this extensively especially around certain edge cases. Meaning, I usually don't use `UserClaims` and `RoleClaims` so I can't guarantee those use cases (fixing problems after identifying them is super easy though, I simply don't have those use cases so I didn't test but if you face any let me know and I'll fix them asap).

So if you're using any of the rarely used features, you'll have to test. But really, I'm comfortable with what I have here running in production 😅

**Comment by mafshin** [comment]
Thank you @mrahhal , I will give it a try
