### ISSUE TITLE
Ambiguous call between AspNetCore.Identity.IdentityBuilder and MR.AspNet.Identity.EntityFramework6.IdentityEntityFrameworkExtensions.AddEntityFrameworkStores<TContext>

### ISSUE THREAD

**Issue by joeizang** [mrahhal/MR.AspNet.Identity.EntityFramework6#6]
Merry Christmas,
I really appreciate what you did creating the MR.*.Int package. I have a problem in my StartUp class with an error which is the subject of this post. This is the section that shows the red squiggly in my startup:

`services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<SchoolDb>()
                .AddDefaultTokenProviders();`
Not sure what I need to do here but was wondering if you could help in any way. Thanks

**Comment by joeizang** [comment]
Sorry man, I just figured out what the issue was, I still had these packages in my project.json:
    "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0"
I removed them, did a dotnet restore and everything is happy.

**Comment by mrahhal** [comment]
No worries. Merry Christmas!
