### ISSUE TITLE
PasswordSignInAsync hangs (deadlock?)

### ISSUE THREAD

**Issue by mapleArm** [mrahhal/MR.AspNet.Identity.EntityFramework6#7]
Hi,
I'm trying use your project with a new .NET Core Application with Identity 3 and .NET framework to connect to an Oracle database.  I was able to create new users with CreateAsync, but the application seems to hang when I try to log in with PasswordSignInAsync.  It seems to be a deadlock issue. Aside from using Oracle database providers and your project, I didn't change much on anything from the out of the box project.

I'm still very new to all of this.  Do you have any recommendations?

Thanks much in advance!

**Comment by mrahhal** [comment]
Hi,
Oracle database? As in mysql or something? Hmm this package is database agnostic as long as you have a supported database provider, so it should all work.

Are you sure it's a deadlock? Can you run the app in debug mode and break when the deadlock is seemingly happening? That way you can see the stack trace of the method that is hanging.

**Comment by mapleArm** [comment]
Hi,
Yes oracle and i can see the users being created in the database using the function CreateAsync.  I ran the app  in debug mode. When I try to log  in, the code gets to PasswordSignInAsync(...) and then steps out of the code and back to the browser where the login page is just a blank screen.  There are no error messages or exceptions in the stack on the server side or in the client side as I would have expected.

**Comment by mrahhal** [comment]
So it's not blocking at `PasswordSignInAsync()`? If the data is being created, then what is causing a blank screen? Can you please provide more information about the issue. Is the problem about the method hanging or is the authentication failing for some reason?

**Comment by mapleArm** [comment]
The blank screen comes when I try to use PasswordSignInAsync().  I think the problem is about the method hanging.  The credentials look fine so I don't think the authenticatin is failing for some reason.



Here's some of the code in AccountController:
This is just generic out of the box code.  (I also switched the project from an in memory database to use an Oracle database in applicationdbcontext.cs and startup.cs)



         public async Task<IActionResult> Login(LoginViewModel model, string returnUrl = null)
         {
            ViewData["ReturnUrl"] = returnUrl;
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation(1, "User logged in.");
                    return RedirectToLocal(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToAction(nameof(SendCode), new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning(2, "User account locked out.");
                    return View("Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return View(model);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

**Comment by mrahhal** [comment]
I still need to know where exactly the error is happening inside the `PasswordSignInAsync` method, and what exactly is the error. I still don't know if an exception is being thrown or if something else is happening, the method can't be hanging or else you won't get a page (blank or not) at all. It could be an exception, do you have the google chrome inspector open when issuing the request? If not, open it to the Network tab, and check "Preserve log", and then hit sign in and see the response status. You might be getting a 500 or something (if so, the exception stack trace should show up).

If you're already doing that, ugh I really don't know, I believe it must be an exception. If the browser stops loading the page and a "blank" page is appearing, then nothing is hanging.

I have some suspicions but I'll leave them till after you check the exception.

**Comment by mapleArm** [comment]
PasswordSignInAsync ()  is a function in the Microsoft.AspNetCore.Identity package and so I can't see inside the function.  
I'll  opened chrome and used the inspector.  In the network tab, I checked "Preseverve log" and then tried logging in.  Nothing shows up.  No response rows with names/status/etc. as you and I would expect.

Thanks again for your help.

**Comment by mapleArm** [comment]
I tried in firefox and i can see a 500 status error

The raw response header is 
Content-Length: 0
Date: Mon, 09 Jan 2017 21:40:19 GMT
Server: Kestrel
X-Powered-By: ASP.NET
X-SourceFiles: =?UTF-8?B?YzpcdXNlcnNccGV0ZS5odXluaFxkb2N1bWVudHNcdmlzdWFsIHN0dWRpbyAyMDE1XFByb2plY3RzXE9yYWNsZUlkZW50aXR5UE9DXHNyY1xPcmFjbGVJZGVudGl0eVBPQ1xBY2NvdW50XExvZ2lu?=

**Comment by mrahhal** [comment]
Okay, that's good. You're running in development, if you've setup `app.UseDeveloperExceptionPage()` correctly you should see a detailed error page with stack trace info (or at least the error in the request information), not just a raw 500.

I'd guess that problem is inside some feature that I haven't been using (maybe two-factor, I think that it can be easily fixed but I'll need you to confirm the actual stack trace of the exception).

**Comment by mrahhal** [comment]
I'm closing this, please reopen if you still have issues.
