### ISSUE TITLE
TUser Constraint violation problem when running aspnet core app

### ISSUE THREAD

**Issue by joeizang** [mrahhal/MR.AspNet.Identity.EntityFramework6#8]
Hello there,
I just tried to run my application for the first time and this is the inner exception I got. It doesn't let me start the application at all. It just stops and gives me this exception.

For context, my system is Windows 10 Home, VS 2015 Update 3, project is created against the full .NetFramework 4.6.1 and all the packages are updated to v1.1.0. 
The error occurs here:

```cs
services.AddIdentity<ApplicationUser, IdentityRole>()
    .AddEntityFrameworkStores<SchoolDb>()
    .AddDefaultTokenProviders();
```
This is the exception that gets produced when I try to run the application.

```
GenericArguments[0], 'SwiftSkool.Models.ApplicationUser', on  'MR.AspNet.Identity.EntityFramework6.UserStore`8[TUser,TRole,TUserRole,TUserClaim,TUserLogin,TRoleClaim,TContext,TKey]' violates the constraint of type parameter 'TUser'.
```

**Comment by mrahhal** [comment]
Hi,

Are you sure your `ApplicationUser` extends `IdentityUser` and has a default parameterless ctor?

**Comment by joeizang** [comment]
Yes, My ApplicationUser extends IdentityUserInt and I have a role class called ApplicationRole which extends IdentityRoleInt. Both don't have ctors which I suppose means an implicit parameterless constructor right?

**Comment by mrahhal** [comment]
Ah  you're using the new *Int classes. That's right, they'll have default ctors.
OK, this is absolutely a violation of the type parameter constraints on your part. Did you check the sample [`Key.Int`](/mrahhal/MR.AspNet.Identity.EntityFramework6/tree/master/samples/Key.Int) to see how to do this? Your DbContext should also extend `IdentityDbContextInt`, maybe that's the problem. If all fails, show me your `ApplicationUser`, `ApplicationRole`, and `SchoolDb`.

**Comment by joeizang** [comment]
Ok i will check and will let you know what i encounter. Thanks

**Comment by joeizang** [comment]
So I checked and everything seems okay. Here are my classes shortened for space:

```cs
public class SchoolDb : IdentityDbContextInt<ApplicationUser>
{
    public static string ConnectionString { get; set; } = "Server=(localdb)\\mssqllocaldb;Database=aspnet-SwiftSkool-1f2660e9-f90c-4810-b8d8-    8e3d246a3826;Trusted_Connection=True;MultipleActiveResultSets=true";
    public SchoolDb(string connectionstring)
        : base(ConnectionString)
    {
    }

    protected override void OnModelCreating(DbModelBuilder builder)
    {
        base.OnModelCreating(builder);
        // Customize the ASP.NET Identity model and override the defaults if needed.
        // For example, you can rename the ASP.NET Identity table names and more.
        // Add your customizations after calling base.OnModelCreating(builder);
    }

    public DbSet<Guardian> Guardians { get; set; }
    public DbSet<BehaviourActivity> BehaviourActivities { get; set; }
    public DbSet<Rating> Ratings { get; set; }
}
```

```cs
public class ApplicationUser : IdentityUserInt
{
    public int StateId { get; set; }
    public State StateOfOrigin { get; set; }
}

public class ApplicationRole : IdentityRoleInt
{
}
```

I even changed IdentityRole to ApplicationRole but still having the same error. Hope we can resolve this as I am stumped over this and don't know what to do

**Comment by mrahhal** [comment]
(I edited your comment, it's really hard to figure things if the formatting is not good, you can check your comment by clicking on edit to see how formatting should look like)

Hmmm everything looks good :/
Are you able to run the samples in this project? If you could create a standalone minimal repository that reproduces this issue on github (and make it close to how your app is structured) I'd be able to help (and I'd probably be able to figure out the problem instantly). I can't really do much otherwise.

**Comment by joeizang** [comment]
Sorry about the comments and bad formatting. My project is simple standard project with automapper and MR.AspNet. so no other class library project just one web application project. I have something like that which works with efcore at github.com/joeizang/SwiftSchool. I just want to move it to EF6 and not EFCore. Maybe I should just use the non int MR.AspNet.Identity.EntityFramework6 and change my primary keys to string. Anyways I will try and create a minimal one and see how it goes. God bless.

**Comment by mrahhal** [comment]
Yup I know what you mean, but trust me even with the simplest of projects (and an asp.net + mvc + ef + automapper can't really be simple), you could've missed something that neither you nor me thought of. But a minimal repro will allow me to instantly spot the issue.

And you don't have to compromise if you really want to use an int as a key. The issue you're facing maybe unrelated to that even.

**Comment by joeizang** [comment]
hi,
I changed everything to the EntityFramework 6 package and stopped using ints for PKs. It starts up the web application but once I try to  either add data or do anything that requires the database like register a user or login, I get an error page saying the model backing the DbContext has changed and thus I need code-first migrations. So dunno what's going on there.  Do you have any ideas? I want to thank you for taking the time to talk with me. I will try and setup the small repo or you could look at my github like I mentioned earlier. That is exactly what I am moving to EF6 that is giving me issues. Clone that and give it a try to change it to use EF6

**Comment by mrahhal** [comment]
If you're able to run the samples without issues, I suggest you deeply compare the setup code between the sample and your app. Start by just creating a custom ApplicationUser and ApplicationDbContext, and follow with the rest by looking at the sample. You should be able to get it to work like that. (If you still can't, I'll need a repro :/)

**Comment by joeizang** [comment]
will do that and let you know. Many thanks for your help. Cheers & God bless

**Comment by mrahhal** [comment]
I'm closing this, please reopen if you still have issues.
