### ISSUE TITLE
please assist with adding claims when a user is authenticated.

### ISSUE THREAD

**Issue by jimmymain** [mrahhal/MR.AspNet.Identity.EntityFramework6#9]
I have tried the mechanisms here
http://benfoster.io/blog/customising-claims-transformation-in-aspnet-core-identity

to add extra claims to an authenticated user.

 * in the first method, using `ClaimsTransformer` in the overridden method `context.Principal.Identity.IsAuthenticated` is never true.
 * in the second method, I am unable to resolve the `RoleManager<IdentityRole> roleManager,` parameter to the `AppClaimsPrincipalFactory` class.
 

Do you have any idea what methods to override to create additional claims when a user is authenticated?

Thanks!

**edit**
I have looked at the code for [UserClaimsPrincipalFactory](https://github.com/aspnet/Identity/blob/release/src/Microsoft.AspNetCore.Identity/UserClaimsPrincipalFactory.cs#L78) and it seems like the right place to *edit* the claims when the user is authenticated. So perhaps I really just need assistance with providing the `RoleManager` dependency for `RoleManager<MR.AspNet.Identity.EntityFramework6.IdentityRole>` that the UserClaimsPrincipalFactory needs?

**Comment by mrahhal** [comment]
I've faced this a long time ago and I think I have the most appropriate solution. In summary, when building the `IServiceCollection` you can simply replace the implementation that was registered by Identity (so after you call `AddIdentity`). There's a `IServiceCollection.Replace` method. You can then provide your own implementation, and you can still use the default Identity implementation by re-adding it to the service collection as its own type. Give me a sec and I'll make an example

**Comment by mrahhal** [comment]
So you really just do something like this:

```cs
// services.AddIdentity ...

services.Replace(
    ServiceDescriptor.Scoped(
        typeof(IUserClaimsPrincipalFactory<AppUser>), typeof(AppUserClaimsPrincipalFactory)));
```

`AppUserClaimsPrincipalFactory` would be your own type implementing `IUserClaimsPrincipalFactory<AppUser>`, you can copy code form the original implementation in Identity and then add your custom claims after that:

```cs

// Inside "AppUserClaimsPrincipalFactory"
public async Task<ClaimsPrincipal> CreateAsync(AppUser user, string authenticationType)
{
    // Copy code from the default implementaion

    // Custom app claims
    id.AddClaim(new Claim(...));

    return new ClaimsPrincipal(id);
}
```

**Comment by jimmymain** [comment]
@mrahhal - first thing, this is an awesome package, allowed me to migrate a bunch of code to core without having to use EF7 (which is immature) this project is critical for my code migration.

I solved the problem by doing the following.
I used this constructor:
```
    public ClaimsPrincipalFactory(
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager,
        IOptions<IdentityOptions> optionsAccessor) : base(userManager, roleManager, optionsAccessor)
    {
```

When I should have used this:
```
    public ClaimsPrincipalFactory(
        UserManager<ApplicationUser> userManager,
        RoleManager<ApplicationRole> roleManager,
        IOptions<IdentityOptions> optionsAccessor) : base(userManager, roleManager, optionsAccessor)
    {
    }
```
I had the wrong kind of role.
Injecting the class was then easy, but it **must** be done after the call to `AddIdentity`

Thanks for the help, the issue is completely resolved, and keep up the awesome work!

**Comment by mrahhal** [comment]
Glad it worked for you, and thanks!
